apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: repset1
spec:
  replicas: 2
  selector: 
    matchLabels:
       env: dev
    matchExpressions:
      - { key: env, operator: In, values: [ dev ] }
  template:
    metadata:
      name: mypod
      labels:
        env: dev
    spec: 
        containers:
         - name: pod1
           image: vimal13/apache-webserver-php
           volumeMounts:
            - mountPath: "/var/www/html"
              name: myvolume1
        volumes: 
          - name: myvolume1
            persistentVolumeClaim:
             claimName: myvolume


